
spring:  datasource:    url: jdbc:mysql://127.0.0.1:3306/testjpa?characterEncoding=utf8&useSSL=false
    username: chenling
    password: chenling
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:  port: 8080 
      
mybatis:  configuration:    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl