server:
  port: 8088
  
spring:  datasource:     url: jdbc:mysql://localhost:3306/house?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: chenling
    password: chenling
    
    
mybatis:  config-location: classpath:/mybatis/mybatis-config.xml